version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: yarn start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    env_file:
      - .development.env
    environment:
      PG_DATA: /docker-entrypoint-initdb.d
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - pg_data:/docker-entrypoint-initdb.d
    restart: always

volumes:
  pg_data:
